apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bank-api.fullname" . }}-db-credentials
  labels:
    {{- include "bank-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  BANK_POSTGRES_HOST: "postgres-postgresql.bank-db.svc.cluster.local"
  BANK_POSTGRES_PORT: "5432"
  BANK_POSTGRES_USERNAME: "postgres"
  BANK_POSTGRES_PASSWORD: "postgres"
  BANK_POSTGRES_DATABASE: "bank"
  BANK_MIGRATE: "true" 