apiVersion: v1
kind: Secret
metadata:
  name: bank-api-db-credentials
  labels:
    {{- include "bank-api.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }} 